development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: akiro
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: akiro
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: akiro
  password: